# Generated by Django 4.2.6 on 2023-11-17 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_attempt', models.DateTimeField(auto_now_add=True, verbose_name='дата и время попытки')),
                ('status', models.CharField(max_length=30, verbose_name='статус попытки')),
                ('server_response', models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.CreateModel(
            name='MailingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_time', models.DateTimeField(verbose_name='время рассылки')),
                ('frequency', models.CharField(choices=[('Daily', 'Раз в день'), ('Weekly', 'Раз в неделю'), ('Monthly', 'Раз в месяц')], max_length=30, verbose_name='периодичность')),
                ('status', models.CharField(choices=[('Created', 'Создана'), ('Started', 'Запущена'), ('Completed', 'Завершена')], max_length=30, verbose_name='статус рассылки')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='тема письма')),
                ('body', models.TextField(verbose_name='тело письма')),
                ('is_active', models.BooleanField(default=True, verbose_name='признак активности')),
                ('client', models.ManyToManyField(to='service_client.client', verbose_name='клиент')),
                ('mailing_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsletter.mailingsettings', verbose_name='настройки')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
        ),
    ]
